### ISSUE TITLE
gff3 error

### ISSUE THREAD

**Issue by Rexomania1** [Sung-Huan/ANNOgesic#16]
Hello, I am trying to use the transcript module of annogesic all week. First of all i keep getting the following error;

root@93fee60e0cf0:/Petya/Rex/petya_paper/ecopAA/output/TSSs/gffs# annogesic transcript -pj /Petya/Rex/petya_paper/ecopAA/ -g /Petya/Rex/petya_paper/ecopAA/input/references/annotations/NC_018666.1.gff -tl $TEX_LIBS -rt all_1 -cf gene CDS -ct /Petya/Rex/petya_paper/ecopAA/output/TSSs/gffs/NC_018666_TSS.gff

       ___    _   ___   ______                  _
      /   |  / | / / | / / __ \____ ____  _____(_)____ \
  __ / /| | /  |/ /  |/ / / / / __ `/ _ \/ ___/ / ___/__\
 |  / ___ |/ /|  / /|  / /_/ / /_/ /  __(__  ) / /__    /
 | /_/  |_/_/ |_/_/ |_/\____/\__, /\___/____/_/\___/   /
 |                          /____/
 |__________________
 |_____________________
 |________________________________________________
 |                                                \
 |________________________________________________/

Running transcript detection
Parsing NC_018666.1.gff
Parsing TEX_plus_div_by_96542.0_multi_by_96542.0_reverse.wig
Parsing TEX_minus_div_by_104934.0_multi_by_96542.0_reverse.wig
Parsing TEX_plus_div_by_96542.0_multi_by_96542.0_forward.wig
Parsing TEX_minus_div_by_104934.0_multi_by_96542.0_forward.wig
Merging wig files of NC_018666.1
Importing tex_notex wig files
Computing transcripts for NC_018666.1
/Petya/Rex/petya_paper/ecopAA//output/transcripts/NC_018666.1_tex_notex
Merging gff files of NC_018666.1
Parsing NC_018666.1_transcript.gff
Merging gff files of NC_018666.1_transcript
Error: There are folders which contain no gff3 files! The files should end with .gff!

PS: all folders contain gff files that as in gff3 format, and the same input gff was used for the TSS and PS prediction. I would be glad if you could help advise me on what do to make it work.

**Comment by Sung-Huan** [comment]
Hi,

The error that you met is really weird for me. Basically, you already finished all the process of transcript detection. The error is due to some intermediate files are not found. I have two suggestions.

1. Please check the version of your ANNOgesic. If it is not latest version, please update the version and run it again.
2. If you still cannot fix it, and you are willing to provide the input files to me, I can take a look of your data. It may have something unusual.
3.  The main process of transcript detection is already finished in your run. If you do not want to provide your input data, you should be still able to get the gff file at /output/transcripts/gffs.

Best,
Sung-Huan

**Comment by Sung-Huan** [comment]
Sorry, I was wrong. The main process is not finished yet. If you can provide me the input files, I can take a look.

**Comment by Rexomania1** [comment]
Hi Sung-Huan,

Attached are the input files. Please take a look for me.

**Comment by Rexomania1** [comment]
[input.zip](https://github.com/Sung-Huan/ANNOgesic/files/4844517/input.zip)
Attached are the input files for your perusal. Thanks

**Comment by Sung-Huan** [comment]
Thanks for the files. I got your error. It is an common issue that users may meet.

The headers can be very different because the input files may come from many different databases. However, we are not able to solve all of the naming issues. If we rename the headers, it may not match the users' needs and cause some misleading. Therefore, we ask the users to check their input files - gff files, wig files and fasta files to make sure all the headers should be matched.

The ideal case is
fasta file:
> Good_Name

wig file:
track type=wiggle_0 name="TEX_minus_forward"
variableStep chrom=Good_Name span=1

gff file
Good_Name RefSeq  gene  .....  

In your case, the headers of wig files are different from gff files.

wig files:
track type=wiggle_0 name="TEX_minus_forward"
variableStep chrom=gi|407484805|ref|NC_018666.1| span=1

gff files:
NC_018666.1

Your wig files are "gi|407484805|ref|NC_018666.1|" and your gff file is NC_018666.1. Moreover, "|" is an used special symbol for Linux. It may cause some confusion for Linux. I guess you downloaded the file via old version of RefSeq. Now RefSeq does not use "|" for header.

It is quite easy to solve the issue. You just need to open the wig file by any editor. Then replace the gi|407484805|ref|NC_018666.1| to NC_018666.1. I already tested it, and the error is gone.

I also upload the renamed wig files to you.

If you download the input files via NIH FTP, ANNOgesic will handle the naming issue. If you download the files by yourself or via other databases, please check the name before running.

[wig.zip](https://github.com/Sung-Huan/ANNOgesic/files/4844723/wig.zip)

**Comment by Rexomania1** [comment]
Thank you for all your responses. I am grateful

**Comment by Rexomania1** [comment]
My final bother for today. I just go this error from promoter prediction. Could you please tell me why;
annogesic promoter -pj $Annogesic/ -t $Annogesic/output/TSSs/gffs/NC_018666_TSS.gff -f $Annogesic/input/references/fasta_files/NC_018666.1.fa -w 45 2-10 -pl 10

       ___    _   ___   ______                  _
      /   |  / | / / | / / __ \____ ____  _____(_)____ \
  __ / /| | /  |/ /  |/ / / / / __ `/ _ \/ ___/ / ___/__\
 |  / ___ |/ /|  / /|  / /_/ / /_/ /  __(__  ) / /__    /
 | /_/  |_/_/ |_/_/ |_/\____/\__, /\___/____/_/\___/   /
 |                          /____/
 |__________________
 |_____________________
 |________________________________________________
 |                                                \
 |________________________________________________/

Running promoter detection
Parsing NC_018666.1.fa
Parsing NC_018666_TSS.gff
Checking gff file of NC_018666_TSS.gff
Merging gff files of NC_018666.1_TSS
Generating fasta file of NC_018666.1
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2230, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2195, in run_MEME
    controller.meme()
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/controller.py", line 710, in meme
    meme.run_meme(args_pro, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/meme.py", line 395, in run_meme
    self._get_upstream(args_pro, prefix, tss, fasta)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/meme.py", line 324, in _get_upstream
    upstream(os.path.join(self.tss_path, tss),
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/TSS_upstream.py", line 85, in upstream
    tsss, seq = read_data(tss_file, fasta_file)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/TSS_upstream.py", line 54, in read_data
    if line[0] == ">":
IndexError: string index out of range

**Comment by Sung-Huan** [comment]
It is due to an empty line (the last line) in your fasta file. Not sure why you have that line. Normally there is no empty line in fasta file. So, you just need to remove that line. Then it should work. I will also put some code for adapting the empty line in the future.

**Comment by Rexomania1** [comment]
Thank you
