### ISSUE TITLE
TAP-only (no TEX) dRNA-seq datasets

### ISSUE THREAD

**Issue by simone-pignotti** [Sung-Huan/ANNOgesic#33]
Hi,

Thanks for developing and maintaining this great tool.
I was wondering whether it would be possible to analyze dRNA-seq datasets which were generated using only TAP, without TEX. An enrichment of reads at 5′ ends should still be detectable, although the signal would probably be weaker.
If you have already tested ANNOgesic on such datasets, do you have any recommendation about the optimization of its parameters?

Thank you!
Simone

**Comment by Sung-Huan** [comment]
Dear Simone,

Thank you for your email. I personally have no experience about TAP
dRNA-Seq. But I think ANNOgesic could still work for that dataset since
their principles are similar. As long as the input format is correct,
ANNOgesic should be able to deal with it. Regarding parameters, it really
depends on the data and also your criteria. I would suggest you use the
default one to see how the performance is. You can also use optimize_tss_ps
to obtain the best parameters based on your manual curation set (only
around 50-100 manual detected TSSs are needed). For the details you can
check our documentation and tutorial:

https://annogesic.readthedocs.io/en/latest/subcommands.html#optimize-tss-ps-optimization-of-tss-and-processing-site-detection
https://annogesic.readthedocs.io/en/latest/tutorial.html#tss-and-processing-site-prediction-and-optimization

Best,
Sung-Huan

simone-pignotti ***@***.***> 於 2022年9月16日 週五 晚上10:09寫道：

**Comment by simone-pignotti** [comment]
Thank you very much Sung-Huan, I will try that!
