### ISSUE TITLE
tex_notex_libs formatting

### ISSUE THREAD

**Issue by gcabebe** [Sung-Huan/ANNOgesic#34]
Hello! First of all, thank you for making this program available for everyone to use.

I'm trying to use ```tss_ps``` on my wig files from RNA-seq data but I'm having troubles with the formatting. This is the format I was using to test out 1 wig file:

```
--tex_notex_libs /home/gcabebe/rnaseq/SRP157937/TestAnalysis/output/pseudomonas_coverage-tnoar_min_normalized/SRR7693534.trimmomatic_out_div_by_25687973.0_multi_by_9485079.0_forward.wig:frag:1:a:+
```

When I run it, I get the following error:

```
Running TSS prediction
Error: The --tex_notex_libs was assinged incorrectly. Please check it again.
```

Here's the shell script I was using for testing 1 wig file:
```
#!/bin/bash
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --mem=0
#SBATCH -p long
#SBATCH -t 150:00:00

script=$0
project_path=$1 # /home/gcabebe/rnaseq/SRP157937/annogesic_tss
fasta_files=$2 # /home/gcabebe/rnaseq/SRP157937/TestAnalysis/input/pseudomonas_reference_sequences/Pputida_KT2440_MOD.fna
annotation_files=$3 # /home/gcabebe/rnaseq/SRP157937/TestAnalysis/input/pseudomonas_annotations/Pseudomonas_putida_KT2440_110.gff
tex_notex_libs=$4 # /home/gcabebe/rnaseq/SRP157937/TestAnalysis/output/pseudomonas_coverage-tnoar_min_normalized/SRR7693534.trimmomatic_out_div_by_25687973.0_multi_by_9485079.0_forward.wig:frag:1:a:+
condition_names=$5 # citrate1
replicate_tex=$6 # 1_6

annogesic tss_ps --project_path $project_path --program TSS --tsspredator_path /home/gcabebe/trx_tools/TSSpredator-1.1beta.jar --fasta_files $fasta_files --annotation_files $annotation_files --tex_notex_libs $tex_notex_libs --condition_names $condition_names --replicate_tex $replicate_tex



```
Additionally, I would like to run this program with 48 wig files, and I keep having issues with formatting all of them on a shell script. Is there an efficient way of running all 48 wig file assignments at once?

**Comment by Sung-Huan** [comment]
Hi,

Generally, dRNA-seq should contain TEX+ and TEX- libraries with their corresponding forward and reverse strand. But in your command, there is only one TEX+ library assigned. Therefore, it cause an error. Please make sure you have correct file type. Using dRNA-seq libs, the assignment will be like the following:

TEX_LIBS="$WIG_FOLDER/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_minus.wig:notex:1:a:- \
$WIG_FOLDER/GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_minus.wig:tex:1:a:- \
$WIG_FOLDER/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_plus.wig:notex:1:a:+ \
$WIG_FOLDER/GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_plus.wig:tex:1:a:+"

If your files are not dRNA-seq lib but conventional RNA-seq, you can assign them like the following:

LIBS="ANNOgesic/input/wigs/fragment/S1_1_reverse.wig:frag:1:a:- \
ANNOgesic/input/wigs/fragment/S1_1_forward.wig:frag:1:a:+ \
ANNOgesic/input/wigs/fragment/S1_2_reverse.wig:frag:1:b:- \
ANNOgesic/input/wigs/fragment/S1_2_forward.wig:frag:1:b:+ \
ANNOgesic/input/wigs/fragment/S2_1_reverse.wig:frag:2:a:- \
ANNOgesic/input/wigs/fragment/S2_1_forward.wig:frag:2:a:+ \
ANNOgesic/input/wigs/fragment/S2_2_reverse.wig:frag:2:b:- \
ANNOgesic/input/wigs/fragment/S2_2_forward.wig:frag:2:b:+ \ 

In the above libraries, we have two experimental conditions (1 and 2) with two replicates each (a and b). Moreover, both conditions have forward (+) and reverse (-) strand.

For your 48 wig files, the first thing you have to do is making sure how to assign these 48 files. Are they all different conditions? Do they contain replicates? or are they TEX+/- libs?

If you want to consider 48 files together (all files will be used to detect genomic features), you can follow the two formats that I posted above. But please make sure these 48 files can used together without conflicts. Otherwise, you may obtain nothing or many false positives. And also you may need to pay attention on the memory of your machine.

Furthermore, if your library is not dRNA-seq but conventional RNA-seq, some functions cannot be used such as tss_ps.

For the details of file format and TSS prediction, you can check our documentation and tutorial.

https://annogesic.readthedocs.io/en/latest/tutorial.html#tss-and-processing-site-prediction-and-optimization
https://annogesic.readthedocs.io/en/latest/subcommands.html#the-format-of-filename-1

Best,
Sung-Huan

**Comment by gcabebe** [comment]
Thank you for the response,

I ran tss_ps again with the forward and reverse strand of 1 replicate from a condition and I still get the same error.

The 48 wig files come from a study with 4 different conditions, each condition with 6 replicates, with each replicate having its forward and reverse strand.

But also I wasn't aware that tss_ps can't be used with conventional RNA-seq data, which is what my library is made up of.

**Comment by Sung-Huan** [comment]
Looks like your libs are not from dRNA-Seq. ANNOgesic is not able to use conventional RNA-seq for detecting TSSs currently. Thus, you may not be able to get TSSs via ANNOgesic. We are developing a function for detecting TSSs by using conventional RNA-Seq data. But it may take a while.

But if your goal is to detect sRNAs, you can still use ANNOgesic to obtain such data without TSS information. You can just assign your libs as frag ones, and skip all the arguments related to TSS. Then you can still get the sRNA candidates.

Best
