### ISSUE TITLE
TSSpredator-1.06.jar not found during Docker build

### ISSUE THREAD

**Issue by vdejager** [Sung-Huan/ANNOgesic#35]
I'm trying to rebuild the docker container with ubuntu:focal
However I run into a dependency that is no longer available.
It seems that the repository does not exist anymore. Could you point me to a replacement?

Removing intermediate container 9c9d0d613ae6
 ---> 0024190f61df
Step 17/60 : RUN wget https://lambda.informatik.uni-tuebingen.de/nexus/content/repositories/releases/org/uni-tuebingen/it/TSSpredator/1.06/TSSpredator-1.06.jar && cp TSSpredator-1.06.jar /usr/local/bin/TSSpredator.jar
 ---> Running in 6d3831448c98
--2022-11-03 08:47:48--  https://lambda.informatik.uni-tuebingen.de/nexus/content/repositories/releases/org/uni-tuebingen/it/TSSpredator/1.06/TSSpredator-1.06.jar
Resolving lambda.informatik.uni-tuebingen.de (lambda.informatik.uni-tuebingen.de)... 134.2.9.13
Connecting to lambda.informatik.uni-tuebingen.de (lambda.informatik.uni-tuebingen.de)|134.2.9.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-03 08:47:50 ERROR 404: Not Found.

**Comment by Sung-Huan** [comment]
Hi,

I updated the Dockerfile for latest version of TSSpredator.
I have to say, some packages which arguments/parameters are changed in the latest version. Thus, if the packages are missing and their input arguments are also changed in the latest version, some errors may occur. So, I would suggest to use "pull" instead of rebuild a new image.

docker pull silasysh/annogesic

For TSSpredator, we already edit the code for adjusting the latest version of TSSpredator.

Best,
Sung-Huan
