### ISSUE TITLE
annogesic from nanopore transcriptomic output

### ISSUE THREAD

**Issue by cmetadea** [Sung-Huan/ANNOgesic#39]
Hi, I was just wondering if ANNOgesic is able to handle data received from nanopore RNA-seq output? If I can map outside the pipeline and provide wig files directly, also if the data is not stranded (as in direct cDNA sequencing), how do I do it?

Thanks!

**Comment by Sung-Huan** [comment]
Hi,

I have never run ANNOgesic for nanopore transcriptomics data before. In principle, if the input data is wiggle file format, ANNOgesic should be able to manage the analysis. However, the accuracy cannot be promised. Perhaps, some parameters need to be changed. If you want you can give it a shot.

Regarding non-stranded data, it needs several manual modifications before running ANNOgesic.
1. duplicate you input libraries to another copy. One copy is assigned to forward strand and the other one is for reverse strand.
2. the reverse strand libraries should change the name and add negative signs "-" in front of all numbers, for example:
forward strand (original dataset):
track type=wiggle_0 name="S1_1_forward"
variableStep chrom=NC_002929.2 span=1
1 3.0271648823
2 4.86051826171
3 5.20160726254
4 5.20160726254
5 5.20160726254
6 5.20160726254
7 5.62796851356
8 6.82178001644

reverse strand (duplicated dataset):
track type=wiggle_0 name="S1_1_**_reverse_**"
variableStep chrom=NC_002929.2 span=1
1 -3.0271648823
2 -4.86051826171
3 -5.20160726254
4 -5.20160726254
5 -5.20160726254
6 -5.20160726254
7 -5.62796851356
8 -6.82178001644

the name is changed from S1_1_forward to S1_1_reverse, and all numbers containing negative signs.

Then you just assign these two libraries to ANNOgesic.

3. Since the data is non-stranded, the UTR-derived and antisense sRNAs cannot be identified. By this way, you can only get intergenic sRNAs. Thus, you can run sRNA detection of ANNOgesic without assigning
--utr_derived_srna or -u. The intergenic sRNAs will be expressed both at forward and reverse strands. But we cannot judge which strand that the sRNA located.

Best,
Sung-Huan

**Comment by cmetadea** [comment]
Thank you! I will try this method.

**Comment by cmetadea** [comment]
Thank you! I will try with this method
