### ISSUE TITLE
sRNA target prediction error

### ISSUE THREAD

**Issue by cmetadea** [Sung-Huan/ANNOgesic#40]
Hi, when running sRNA target prediction I experienced below 

Running RNAplex with NZ_AP019730.1_target_11
Running RNAplex with NZ_AP019730.1_target_7
WARNING: File ' annogesic_analysis/output/sRNA_targets/RNAplex_results/NZ_AP019730.1/RNAplfold/NZ_AP019730.1_srna2_openen ' open error
WARNING: File ' annogesic_analysis/output/sRNA_targets/RNAplex_results/NZ_AP019730.1/RNAplfold/NZ_AP019730.1_srna47_openen ' open error
WARNING: File ' annogesic_analysis/output/sRNA_targets/RNAplex_results/NZ_AP019730.1/RNAplfold/NZ_AP019730.1_srna81_openen ' open error

any idea what went wrong? 
thank you

**Comment by cmetadea** [comment]
Hello, this is the command that I use
`annogesic srna_target --project_path annogesic_analysis --annotation_files annogesic_analysis/input/references/annotations/tn2.gff3 --fasta_files annogesic_analysis/input/references/fasta_files/tn2.fasta --srna_files annogesic_analysis/output/sRNAs/gffs/best_candidates/tn2_sRNA.gff --program IntaRNA RNAplex RNAup -t 20`

this is the fasta file header :
>NZ_AP019730.1 Helicobacter pylori

sRNA header : 
##gff-version 3
NZ_AP019730.1	ANNOgesic	ncRNA

annotation gff header : 
##gff-version 3
#!gff-spec-version 1.21
#!processor NCBI annotwriter
##sequence-region NZ_AP019730.1 1 1604952
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=210

thanks!

**Comment by Sung-Huan** [comment]
The command looks fine for me. Did you use Docker/Singularity to run ANNOgesic or you install all the third party tools to make a standalone version? I guess it may be a version conflict. If you don't mind, please send your input files including tn2.gff3, tn2.fasta, and tn2_sRNA.gff to me. I will take a look. If it is not comfortable for you to send these files to me, you can try to use Docker or Singularity to run ANNOgesic to avoid the version conflict.

**Comment by Sung-Huan** [comment]
Thank you for your files.

I currently finish the run of RNAplex, there is no error. So, I think the error may be caused by version conflict. I have several suggestions for you.

1. Using Docker or Singularity to run ANNOgesic. All the dependencies with suitable version were installed already. You can directly run ANNOgesic without installing any other tools. Please check our documentation - https://annogesic.readthedocs.io/en/latest/docker.html
2. If you still want to use standalone version, please make sure your versions are the same as the following:
ANNOgesic: 1.1.14
Vienna RNA package (containing RNAplex, RNAup, RNAfold, RNAplfold): 2.3.2
IntaRNA: 2.0.4

Sometimes, when the tools updated, the format and parameters will be changed as well. Then the error is shown.

We are currently working on developing other modules. When we are available, we will update ANNOgesic to adapt all up-to-date third party tools.

**Comment by cmetadea** [comment]
I see, I checked the version and it seems the version are different than your recommendation. I have intaRNA version 3.3.2 with viennaRNA version 2.5.1
I will try to run via docker too
Thank you
