### ISSUE TITLE
TSS prediction fails with some cases where the gff files has more than one accession numbers

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#6]
TSS prediction fails in some cases where the gff files has more than one accession numbers (for chromosomes or plasmids)
Happens when checking for overlapping in merging function.
I have 3 different shades of the issue of multi accession numbers in GFF files.
-	Acinetobacter: has 3 accession numbers, passed without errors!
empty results for the last 2 accession numbers
-	Vibrio: exit with error when merging GFFs
line 495, in check_overlap  num_strain[tss.seq_id]["overlap"] += 1
KeyError: 'NC_002505.1'

-	Klebsiella: a step earlier exit with a different error
Checking gff file of GCF_000019565.1_ASM1956v1_genomic.gff
Error: The end point of gene:90974-91231_+ is longer than the length of whole genome.

In this error, I checked the gff file and found that the start site is belonging to another accession number mentioned after.
And that’s why it says out the length.

It works only if I split the annotation files by accession number and make a serparate analysis for each which will be hard to implement in shorter genomic parts like plasmids

![Annotation 2019-06-15 111344](https://user-images.githubusercontent.com/12513051/60032392-b6f8b180-96a6-11e9-9794-79b783cd72de.png)

**Comment by Sung-Huan** [comment]
Thank you for your information. The answers are following:

- Acinetobacter: has 3 accession numbers, passed without errors! empty results for the last 2 accession numbers
A: I checked your wig files, there is no reads mapped on the plasmids. Therefore, no TSS can be detected.

- Vibrio: exit with error when merging GFFs line 495, in check_overlap num_strain[tss.seq_id]["overlap"] += 1 KeyError: 'NC_002505.1'
A: The bug is fixed in 1.0.3.

- Klebsiella: a step earlier exit with a different error Checking gff file of GCF_000019565.1_ASM1956v1_genomic.gff Error: The end point of gene:90974-91231_+ is longer than the length of whole genome.
A: The length of the plasmid is still less than 91231. The length of the plasmid is only 91096. Thus, the error message is correct.

**Comment by elhossary** [comment]
thanks for fixing
